#!/bin/bash
set -eu

if ! charm whoami > /dev/null; then
    echo "Not logged into charm store" 2>&1
    exit 1
fi

URL=$(charm push "$CHARM_BUILD_DIR/$CHARM.charm" "cs:~$NAMESPACE/$CHARM" | yq r - url)
echo "Uploaded: $URL"

RESOURCE="sriov-network-device-plugin-image"
IMAGE=$(yq r "metadata.yaml" "resources.$RESOURCE.upstream-source")
docker pull "$IMAGE"

IMAGE_REV=$(charm attach cs:~"$NAMESPACE"/"$CHARM" --channel unpublished "$RESOURCE=$IMAGE" | tail -n1 | sed -e 's/uploaded revision \([0-9]*\) of.*/\1/')
echo "Attached: $RESOURCE-$IMAGE_REV"

if [ "$CHANNEL" != unpublished ]; then
    IMAGE_NAME=$(charm list-resources cs:~"$NAMESPACE"/"$CHARM" --channel unpublished --format yaml | yq r - [0].name)
    IMAGE_REV=$(charm list-resources cs:~"$NAMESPACE"/"$CHARM" --channel unpublished --format yaml | yq r - [0].revision)

    charm release "$URL" --channel "$CHANNEL" --resource "$IMAGE_NAME"-"$IMAGE_REV"
fi
if [ "$CHANNEL" != unpublished ]; then
    charm release "$URL" --channel "$CHANNEL" --resource "$RESOURCE-$IMAGE_REV"
    echo "Released to: $CHANNEL"
fi
